# ---------- Stage 1: Build the JAR ----------
FROM maven:3.9.8-amazoncorretto-17-al2023 AS build

WORKDIR /app

# Copy project files
COPY pom.xml .
COPY src ./src

# Build the project (skip tests to speed up)
RUN mvn clean package -DskipTests


# ---------- Stage 2: Run the JAR ----------
FROM openjdk:24-slim-bullseye

WORKDIR /app

# Copy JAR from build stage
COPY --from=build /app/target/ramya-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 9090

# Run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
